### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by hong99yy** [tychxn/jd-assistant#107]
遇到这个问题，那个配置文件并没有删除，怎么办呢

Traceback (most recent call last):
  File "F:\jd-assistant-master\main.py", line 3, in <module>
    from jd_assistant import Assistant
  File "F:\jd-assistant-master\jd_assistant.py", line 13, in <module>
    from config import global_config
  File "F:\jd-assistant-master\config.py", line 29, in <module>
    global_config = Config()
  File "F:\jd-assistant-master\config.py", line 12, in __init__
    raise FileNotFoundError("No such file: config.ini")
FileNotFoundError: No such file: config.ini

**Comment by tychxn** [comment]
https://github.com/tychxn/jd-assistant/issues/81

**Comment by hong99yy** [comment]
> #81

路径问题吗？？怎么更改路径？
