### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by jhhuang96** [tychxn/jd-assistant#11]
[2018-11-04 12:32:44] 本次登录需要验证码
验证码:UYNK
[2018-11-04 12:32:52] 请刷新页面后重新提交
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    print(asst.get_item_stock_state(sku_id='35025101345', area='12_984_3383'))
  File "C:\Users\hjh\Downloads\jd-assistant-master\jd_assistant.py", line 328, in get_item_stock_state
    page = self._get_item_detail_page(sku_id)
  File "C:\Users\hjh\Downloads\jd-assistant-master\jd_assistant.py", line 322, in _get_item_detail_page
    page = self.sess.get(url=url, headers=self.headers)
  File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 644, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 644, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 140, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by tychxn** [comment]
京东采用了新的滑动验证码机制，导致原有的账号密码登陆方式失效，请使用APP扫码登陆。

**Comment by jhhuang96** [comment]
@tychxn   这个函数get_item_stock_state 也失效了。

**Comment by tychxn** [comment]
@jhhuang96 get_item_stock_state 我刚刚试了下，没有问题啊，获取商品的库存状态正常，要不你pull一下最新的代码~
