### ISSUE TITLE
编译问题，能不能出个完整版教程。小白使用起来门槛太高了

### ISSUE THREAD

**Issue by wdubaiyu** [tychxn/jd-assistant#120]
Traceback (most recent call last):
  File "./main.py", line 3, in <module>
    from jd_assistant import Assistant
  File "/Users/dubaiyu/Desktop/jd-assistant-master/jd_assistant.py", line 13, in <module>
    from config import global_config
  File "/Users/dubaiyu/Desktop/jd-assistant-master/config.py", line 4, in <module>
    import configparser
ImportError: No module named configparser

**Comment by ColoPaul** [comment]
No module named configparser，不是很清楚么，没有这个模块，你 pip install就好啊

**Comment by wdubaiyu** [comment]
好的谢谢了

**Comment by FPanda** [comment]
python 3自带这个module的，你应该没有用python3。

**Comment by DoveBoy** [comment]
windows10已安装了Python3环境，请问怎么运行？

**Comment by DoveBoy** [comment]
> No module named configparser，不是很清楚么，没有这个模块，你 pip install就好啊

小白一个，请问windows10下已安装了Python3，能直接用pip install吗？
