### ISSUE TITLE
exec_seckill_by_time 报错

### ISSUE THREAD

**Issue by ktownag** [tychxn/jd-assistant#139]
获取到抢购链接以后：
/home/qq/jd-assistant/jd_assistant.py:1307: DeprecationWarning: Call to deprecated function submit_seckill_order.
  if self.submit_seckill_order(sku_id, num):
/home/qq/jd-assistant/jd_assistant.py:1248: DeprecationWarning: Call to deprecated function _gen_seckill_order_data.
  self.seckill_order_data[sku_id] = self._gen_seckill_order_data(sku_id, num)
/home/qq/jd-assistant/jd_assistant.py:1192: DeprecationWarning: Call to deprecated function _get_seckill_init_info.
  self.seckill_init_info[sku_id] = self._get_seckill_init_info(sku_id)
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    asst.exec_seckill_by_time(sku_ids=sku_ids, buy_time='2020-05-28 09:59:59.050', retry=30, interval=0.01)  # 根据商品是否有货自动下单
  File "/home/qq/jd-assistant/util.py", line 207, in new_func
    return func(*args, **kwargs)
  File "/home/qq/jd-assistant/jd_assistant.py", line 1335, in exec_seckill_by_time
    self.exec_seckill(sku_id, retry, interval, num, fast_mode)
  File "/home/qq/jd-assistant/util.py", line 207, in new_func
    return func(*args, **kwargs)
  File "/home/qq/jd-assistant/jd_assistant.py", line 1307, in exec_seckill
    if self.submit_seckill_order(sku_id, num):
  File "/home/qq/jd-assistant/util.py", line 207, in new_func
    return func(*args, **kwargs)
  File "/home/qq/jd-assistant/jd_assistant.py", line 1248, in submit_seckill_order
    self.seckill_order_data[sku_id] = self._gen_seckill_order_data(sku_id, num)
  File "/home/qq/jd-assistant/util.py", line 207, in new_func
    return func(*args, **kwargs)
  File "/home/qq/jd-assistant/jd_assistant.py", line 1192, in _gen_seckill_order_data
    self.seckill_init_info[sku_id] = self._get_seckill_init_info(sku_id)
  File "/home/qq/jd-assistant/util.py", line 207, in new_func
    return func(*args, **kwargs)
  File "/home/qq/jd-assistant/jd_assistant.py", line 1180, in _get_seckill_init_info
    return parse_json(resp.text)
  File "/home/qq/jd-assistant/util.py", line 122, in parse_json
    return json.loads(s[begin:end])
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by tychxn** [comment]
可能是JD的接口有变动之类的，商品id发一下，我晚点查一下

**Comment by ktownag** [comment]
感谢回复。商品id：100012043978
________________________________

**Comment by ferrenLee** [comment]
大佬您好，我现在遇到了同样的问题，商品ID是100012043978

**Comment by crazyIceChen** [comment]
你好 我也遇到了相同的问题
