### ISSUE TITLE
请问预约商品现在是否可以抢购

### ISSUE THREAD

**Issue by hulengjing** [tychxn/jd-assistant#15]
我这里预约商品出现json错误
  File "D:\python\Python3\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "D:\python\Python3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\python\Python3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

问题出在这个代码
asst.exec_seckill(sku_id='100000822965', retry=30, interval=1)

**Comment by tychxn** [comment]
抢购的代码已更新，本地测试没有问题，但是需要提前手工预约。
最近太忙了，不好意思……

**Comment by AnnitYang** [comment]
[2018-11-30 16:30:05] 登录成功
[2018-11-30 16:30:05] 准备抢购商品:251837
[2018-11-30 16:30:05] 正在等待到达设定时间:2018-11-30 20:00:00
[2018-11-30 20:00:00] 时间达到，开始执行……
Traceback (most recent call last):
  File "C:\jd-assistant-master\main.py", line 10, in <module>
    asst.exec_seckill_by_time(sku_id='251837', buy_time='2018-11-30 20:00:00.000', retry='800', interval='4')
  File "C:\jd-assistant-master\jd_assistant.py", line 906, in exec_seckill_by_time
    for count in range(1, retry + 1):
TypeError: can only concatenate str (not "int") to str
请问这种情况应该如何处理？python白痴一枚，见谅

**Comment by tychxn** [comment]
@AnnitYang 
`asst.exec_seckill_by_time(sku_id='251837', buy_time='2018-11-30 20:00:00.000', retry='800', interval='4')` 
改为
`asst.exec_seckill_by_time(sku_id='251837', buy_time='2018-11-30 20:00:00.000', retry=800, interval=4)`
