### ISSUE TITLE
现在是不是已经普遍无法抢购了？

### ISSUE THREAD

**Issue by e68862230** [tychxn/jd-assistant#154]
一直是获取抢购链接失败，试了几个抢购商品都是这样。。

**Comment by aryaky** [comment]
这个代码的抢购是把货品直接放到购物车，当前的抢购流程（起码380是）到了时间抢购按钮可用，然后到达提交订单界面，应该操作方式变了。

**Comment by e68862230** [comment]
> 这个代码的抢购是把货品直接放到购物车，当前的抢购流程（起码380是）到了时间抢购按钮可用，然后到达提交订单界面，应该操作方式变了。

试了跳过获取抢购按钮状态的步骤，直接提交订单好像会返回空。那现在应该加入购物车，然后直接提交订单么？

**Comment by e68862230** [comment]
> 这个代码的抢购是把货品直接放到购物车，当前的抢购流程（起码380是）到了时间抢购按钮可用，然后到达提交订单界面，应该操作方式变了。

两个流程都试过了，购物车下单和抢购按钮可用后下单，都不行

**Comment by 764763903a** [comment]
还能抢茅台 测试过了

**Comment by e68862230** [comment]
> 还能抢茅台 测试过了

具体怎么操作呢？

**Comment by e68862230** [comment]
@764763903a 具体怎么操作呢？

**Comment by COOLSHARPMAN** [comment]
现在好像这个获取函数没了getTakId();



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "e68862230"<notifications@github.com&gt;; 
发送时间: 2020年10月16日(星期五) 上午10:14
收件人: "tychxn/jd-assistant"<jd-assistant@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [tychxn/jd-assistant] 现在是不是已经普遍无法抢购了？ (#154)





  
还能抢茅台 测试过了
  
具体怎么操作呢？
 
&mdash;

**Comment by e68862230** [comment]
@COOLSHARPMAN  takid还是可以获取的，在cookie里

**Comment by JesseWeb** [comment]
> 还能抢茅台 测试过了

求方法

**Comment by COOLSHARPMAN** [comment]
riskControl都找不到了吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JesseWeb"<notifications@github.com&gt;; 
发送时间: 2020年10月19日(星期一) 下午4:02
收件人: "tychxn/jd-assistant"<jd-assistant@noreply.github.com&gt;; 
抄送: "Vi"<20898526@QQ.COM&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [tychxn/jd-assistant] 现在是不是已经普遍无法抢购了？ (#154)





  
还能抢茅台 测试过了
  
求方法
 
&mdash;

**Comment by YangSugar** [comment]
> @COOLSHARPMAN takid还是可以获取的，在cookie里

茅台不是只能app抢吗 这个可以用吗

**Comment by chenchen529** [comment]
> 还能抢茅台 测试过了

哥们，怎么操作，调用哪个方法。

**Comment by chlon1990** [comment]
> 
> 
> 还能抢茅台 测试过了

你用的哪个function抢茅台啊。。我试了都不行呢

**Comment by crazyIceChen** [comment]
> 还能抢茅台 测试过了

你好，我这边测试报错 ，你有修改什么吗
Users/ice/Downloads/jd-assistant-master/jd_assistant.py:1307: DeprecationWarning: Call to deprecated function submit_seckill_order.
  if self.submit_seckill_order(sku_id, num):
/Users/ice/Downloads/jd-assistant-master/jd_assistant.py:1248: DeprecationWarning: Call to deprecated function _gen_seckill_order_data.
  self.seckill_order_data[sku_id] = self._gen_seckill_order_data(sku_id, num)
/Users/ice/Downloads/jd-assistant-master/jd_assistant.py:1192: DeprecationWarning: Call to deprecated function _get_seckill_init_info.
  self.seckill_init_info[sku_id] = self._get_seckill_init_info(sku_id)
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    asst.exec_seckill_by_time(
  File "/Users/ice/Downloads/jd-assistant-master/util.py", line 207, in new_func
    return func(*args, **kwargs)
  File "/Users/ice/Downloads/jd-assistant-master/jd_assistant.py", line 1335, in exec_seckill_by_time
    self.exec_seckill(sku_id, retry, interval, num, fast_mode)
  File "/Users/ice/Downloads/jd-assistant-master/util.py", line 207, in new_func
    return func(*args, **kwargs)
  File "/Users/ice/Downloads/jd-assistant-master/jd_assistant.py", line 1307, in exec_seckill
    if self.submit_seckill_order(sku_id, num):
  File "/Users/ice/Downloads/jd-assistant-master/util.py", line 207, in new_func
    return func(*args, **kwargs)
  File "/Users/ice/Downloads/jd-assistant-master/jd_assistant.py", line 1248, in submit_seckill_order
    self.seckill_order_data[sku_id] = self._gen_seckill_order_data(sku_id, num)
  File "/Users/ice/Downloads/jd-assistant-master/util.py", line 207, in new_func
    return func(*args, **kwargs)
  File "/Users/ice/Downloads/jd-assistant-master/jd_assistant.py", line 1192, in _gen_seckill_order_data
    self.seckill_init_info[sku_id] = self._get_seckill_init_info(sku_id)
  File "/Users/ice/Downloads/jd-assistant-master/util.py", line 207, in new_func
    return func(*args, **kwargs)
  File "/Users/ice/Downloads/jd-assistant-master/jd_assistant.py", line 1180, in _get_seckill_init_info
    return parse_json(resp.text)
  File "/Users/ice/Downloads/jd-assistant-master/util.py", line 122, in parse_json
    return json.loads(s[begin:end])
  File "/usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by YoungYang2014** [comment]
是的  不能用了

**Comment by COOLSHARPMAN** [comment]
不能用了, jd肯定有新规则了, 大家自己改吧
