### ISSUE TITLE
抢购有和我一样的问题的么？

### ISSUE THREAD

**Issue by 17091002603** [tychxn/jd-assistant#167]
2020-12-29 10:00:04,020 INFO: 登录成功
D:\download\jd-assistant-master\mainQg.py:23: DeprecationWarning: Call to deprecated function exec_seckill.
  asst.exec_seckill(sku_id=sku_ids)
2020-12-29 10:00:04,021 INFO: 第[1/4]次尝试抢购商品:100012043978
D:\download\jd-assistant-master\jd_assistant.py:1303: DeprecationWarning: Call to deprecated function request_seckill_url.
  self.request_seckill_url(sku_id)
D:\download\jd-assistant-master\jd_assistant.py:1134: DeprecationWarning: Call to deprecated function _get_seckill_url.
  self.seckill_url[sku_id] = self._get_seckill_url(sku_id)
2020-12-29 10:00:05,110 INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100012043978&sn=bc054bcf1ab58b399ee5be48a2798b6a&from=pc
D:\download\jd-assistant-master\jd_assistant.py:1307: DeprecationWarning: Call to deprecated function submit_seckill_order.
  if self.submit_seckill_order(sku_id, num):
D:\download\jd-assistant-master\jd_assistant.py:1248: DeprecationWarning: Call to deprecated function _gen_seckill_order_data.
  self.seckill_order_data[sku_id] = self._gen_seckill_order_data(sku_id, num)
D:\download\jd-assistant-master\jd_assistant.py:1192: DeprecationWarning: Call to deprecated function _get_seckill_init_info.
  self.seckill_init_info[sku_id] = self._get_seckill_init_info(sku_id)
Traceback (most recent call last):
  File "D:\download\jd-assistant-master\mainQg.py", line 23, in <module>
    asst.exec_seckill(sku_id=sku_ids)
  File "D:\download\jd-assistant-master\util.py", line 208, in new_func
    return func(*args, **kwargs)
  File "D:\download\jd-assistant-master\jd_assistant.py", line 1307, in exec_seckill
    if self.submit_seckill_order(sku_id, num):
  File "D:\download\jd-assistant-master\util.py", line 208, in new_func
    return func(*args, **kwargs)
  File "D:\download\jd-assistant-master\jd_assistant.py", line 1248, in submit_seckill_order
    self.seckill_order_data[sku_id] = self._gen_seckill_order_data(sku_id, num)
  File "D:\download\jd-assistant-master\util.py", line 208, in new_func
    return func(*args, **kwargs)
  File "D:\download\jd-assistant-master\jd_assistant.py", line 1195, in _gen_seckill_order_data
    default_address = init_info['addressList'][0]  # 默认地址dict
KeyError: 'addressList'

**Comment by luyehui** [comment]
偶尔会有，感觉是cookies的问题

**Comment by Miki162** [comment]
重新登陆一下就好了,是没有获取到登录信息,你可以直接调用asst._get_seckill_init_info(sku_id=sku_ids)这个方法,看一下返回值对不对

**Comment by 17091002603** [comment]
> 重新登陆一下就好了,是没有获取到登录信息,你可以直接调用asst._get_seckill_init_info(sku_id=sku_ids)这个方法,看一下返回值对不对

我现在调用的是这个方法 asst.exec_seckill(sku_id=sku_ids)   我看到登录信息是存到一个文件里了啊  正常的 商品加购物车 然后提交订单我这是没问题的 
（asst.buy_item_in_stock(sku_ids=sku_ids, area=area, wait_all=False, stock_interval=5)  # 根据商品是否有货自动下单）  只是抢购不能用

**Comment by Miki162** [comment]
![image](https://user-images.githubusercontent.com/71741675/103392550-68f52180-4b59-11eb-8854-e0fa5884dd18.png)

**Comment by Miki162** [comment]
def _get_seckill_init_info(self, sku_id, num=1):
        """获取秒杀初始化信息（包括：地址，发票，token）
        :param sku_id:
        :param num: 购买数量，可选参数，默认1个
        :return: 初始化信息组成的dict
        """
        url = 'https://marathon.jd.com/seckillnew/orderService/pc/init.action'
        data = {
            'sku': sku_id,
            'num': num,
            'isModifyAddress': 'false',
        }
        headers = {
            'User-Agent': self.user_agent,
            'Host': 'marathon.jd.com',
        }
        resp = self.sess.post(url=url, data=data, headers=headers)
        logger.info("获取秒杀初始化信息"+resp.text)
        return parse_json(resp.text)
你在这个方法里加个打印,然后调用一下这个方法,看一下返回值,他这个是根据你的账号信息去获取的默认地址,跟村的文件没关系

**Comment by 17091002603** [comment]
> def _get_seckill_init_info(self, sku_id, num=1):
> """获取秒杀初始化信息（包括：地址，发票，token）
> :param sku_id:
> :param num: 购买数量，可选参数，默认1个
> :return: 初始化信息组成的dict
> """
> url = 'https://marathon.jd.com/seckillnew/orderService/pc/init.action'
> data = {
> 'sku': sku_id,
> 'num': num,
> 'isModifyAddress': 'false',
> }
> headers = {
> 'User-Agent': self.user_agent,
> 'Host': 'marathon.jd.com',
> }
> resp = self.sess.post(url=url, data=data, headers=headers)
> logger.info("获取秒杀初始化信息"+resp.text)
> return parse_json(resp.text)
> 你在这个方法里加个打印,然后调用一下这个方法,看一下返回值,他这个是根据你的账号信息去获取的默认地址,跟村的文件没关系

试了下 第一次没有获取到我的用户信息 我把cookie文件删除重新扫码登录了下 可以获取到我的 收货信息 
2020-12-31 11:22:08,989 INFO: 登录成功
D:\download\jd-assistant-master\mainQg.py:24: DeprecationWarning: Call to deprecated function _get_seckill_init_info.
  asst._get_seckill_init_info(sku_ids)
2020-12-31 11:22:12,188 INFO: 获取秒杀初始化信息{"addressList":[{"addressDetail":"中关村科技园区光机****************","addressName":"XXX","areaCode":"86","cityId":2809,"cityName":

**Comment by Miki162** [comment]
那就对了,就是没有用户信息

**Comment by 17091002603** [comment]
> 那就对了,就是没有用户信息

那我明天 用之前  在重新 扫码登录下试试 看看还报不报别的错误  你那里代码可以正常抢购是吧？

**Comment by 17091002603** [comment]
> 那就对了,就是没有用户信息

方便加个微信不  以后有问题沟通下  哈哈 我的名字是微信号

**Comment by Miki162** [comment]
加你了

**Comment by showtimesKing** [comment]
> def _get_seckill_init_info(self, sku_id, num=1):
> """获取秒杀初始化信息（包括：地址，发票，token）
> :param sku_id:
> :param num: 购买数量，可选参数，默认1个
> :return: 初始化信息组成的dict
> """
> url = 'https://marathon.jd.com/seckillnew/orderService/pc/init.action'
> data = {
> 'sku': sku_id,
> 'num': num,
> 'isModifyAddress': 'false',
> }
> headers = {
> 'User-Agent': self.user_agent,
> 'Host': 'marathon.jd.com',
> }
> resp = self.sess.post(url=url, data=data, headers=headers)
> logger.info("获取秒杀初始化信息"+resp.text)
> return parse_json(resp.text)
> 你在这个方法里加个打印,然后调用一下这个方法,看一下返回值,他这个是根据你的账号信息去获取的默认地址,跟村的文件没关系

这里报jsonencodeerror错误,能提供下解决方式嘛?

**Comment by showtimesKing** [comment]
> 加你了

一样的问题能给个解决方式吗？

**Comment by Miki162** [comment]
> > 加你了
> 
> 一样的问题能给个解决方式吗？

删除cookie之后重新登录，应该就能解决了
