### ISSUE TITLE
req.txt库已经安装，但还是报出没有这个模块的错误，用你之前mater的分支就没事，怀疑兼容性错

### ISSUE THREAD

**Issue by zhangsiying2001** [tychxn/jd-assistant#176]
Traceback (most recent call last):
  File "D:/1_Sour/PY1/京东抢票/jd-assistant-master/main.py", line 3, in <module>
    from jd_assistant import Assistant
  File "D:\1_Sour\PY1\京东抢票\jd-assistant-master\jd_assistant.py", line 18, in <module>
    from util import (
  File "D:\1_Sour\PY1\京东抢票\jd-assistant-master\util.py", line 12, in <module>
    from Crypto.PublicKey import RSA
ModuleNotFoundError: No module named 'Crypto'

进程已结束,退出代码1

**Comment by zhangsiying2001** [comment]
(venv) D:\1_Sour\PY1>pip3 uninstall pycrypto
WARNING: Skipping pycrypto as it is not installed.

(venv) D:\1_Sour\PY1>pip3 uninstall crypto
WARNING: Skipping crypto as it is not installed.
卸载上面两个先 
pip install -i https://pypi.doubanio.com/simple/ pycryptodome

之后
  File "D:\1_Sour\PY1\京东抢票\jd-assistant\jd_assistant.py", line 49, in __init__
    raise AsstException('请在 config.ini 中配置 eid, fp, track_id, risk_control 参数，具体请参考 wiki-常见问题')
exception.AsstException: 请在 config.ini 中配置 eid, fp, track_id, risk_control 参数，具体请参考 wiki-常见问题
