### ISSUE TITLE
无法找到Crypto模块（No module named 'Crypto'）

### ISSUE THREAD

**Issue by Elise-Asaloria** [tychxn/jd-assistant#180]
PS C:\Users\Yukari\Downloads\jd-assistantV2-master> python.exe .\Qianggou.txt
Traceback (most recent call last):
File ".\Qianggou.txt", line 1, in <module>
from jd_assistant import Assistant
File "C:\Users\Yukari\Downloads\jd-assistantV2-master\jd_assistant.py", line 18, in <module>
from util import (
File "C:\Users\Yukari\Downloads\jd-assistantV2-master\util.py", line 13, in <module>
from Crypto.PublicKey import RSA
ModuleNotFoundError: No module named 'Crypto'
PS C:\Users\Yukari\Downloads\jd-assistantV2-master>

**Comment by huaisha1224** [comment]
pip install pycryptodome
pip install crypto
pip install pycrypto
安装一下

**Comment by 877801363** [comment]
找到crypto目录，然后把小写的C改成大写的C即可
