### ISSUE TITLE
报非法的十六进制

### ISSUE THREAD

**Issue by narutoexception** [tychxn/jd-assistant#221]
python3 main.py
Traceback (most recent call last):
  File "/Users/lay/python/jd-assistant-master/main.py", line 3, in <module>
    from jd_assistant import Assistant
  File "/Users/lay/python/jd-assistant-master/jd_assistant.py", line 18, in <module>
    from util import (
  File "/Users/lay/python/jd-assistant-master/util.py", line 12, in <module>
    from Crypto.PublicKey import RSA
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/Crypto/PublicKey/__init__.py", line 21, in <module>
    from Crypto.Util.asn1 import (DerSequence, DerInteger, DerBitString,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/Crypto/Util/asn1.py", line 27, in <module>
    from Crypto.Util.number import long_to_bytes, bytes_to_long
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/Crypto/Util/number.py", line 399
    s = pack('>I', n & 0xffffffffL) + s
                                ^
SyntaxError: invalid hexadecimal literal

**Comment by ZhouXiaoLiu** [comment]
我也是这个问题，楼主目前解决了吗

**Comment by ZhouXiaoLiu** [comment]
> 
这个错误是因为在代码中使用了Python 2的旧的语法，在Python 3中会导致语法错误。

在Python 2中，整数字面值后面的L用于指示长整数（long integer）。而在Python 3中，整数字面值不再需要后缀L来表示长整数。因此，在这个代码片段中，0xffffffffL应该被简化为0xffffffff。
说白了这个三方库用的py2语法，也不知道为啥标注的用的python3环境，这个项目可能老久没有维护了，要用得靠自己改了

**Comment by qingyuchan** [comment]
所有的Crypto删除，重新安装下pycryptodome库
