### ISSUE TITLE
GBK编码问题。如何解决。百度了下 没啥思路。

### ISSUE THREAD

**Issue by zrad** [tychxn/jd-assistant#24]
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from jd_assistant import Assistant
  File "F:\jdqg\jd_assistant.py", line 12, in <module>
    from config import global_config
  File "F:\jdqg\config.py", line 19, in <module>
    global_config = Config()
  File "F:\jdqg\config.py", line 13, in __init__
    self._config.read(self._path)
  File "D:\Python\Python37\lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "D:\Python\Python37\lib\configparser.py", line 1014, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 14: illegal m
ultibyte sequence

**Comment by tychxn** [comment]
hi，
感谢反馈，Bug已经修复，麻烦再试一下~

![20190227_183647](https://user-images.githubusercontent.com/29301320/53484674-50300680-3abf-11e9-8e67-479e1a391f20.jpg)

**Comment by zrad** [comment]
很快。不知道对京东预约产品支持吗？

**Comment by tychxn** [comment]
当然支持。普通商品或抢购商品都可以，具体教程在wiki中~
