### ISSUE TITLE
运行一段时间后 会出现超时的情况...

### ISSUE THREAD

**Issue by DDFTONE** [tychxn/jd-assistant#53]
Traceback (most recent call last):
  File "C:\Users\Theo\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\Theo\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Users\Theo\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Theo\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "C:\Users\Theo\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Theo\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "C:\Users\Theo\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 316, in connect
    conn = self._new_conn()
  File "C:\Users\Theo\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001B6EA20F6A0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连 接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Theo\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\Theo\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Theo\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='c0.3.cn', port=443): Max retries exceeded with url: /stock?skuId=100006248177&buyNum=1&area=19_1704_1797_37820&ch=1&_=1580224794754&callback=jQuery4673409&extraParam=%7B%22originid%22%3A%221%22%7D&cat=9192%2C12190%2C1517&venderId=1000078145 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001B6EA20F6A0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 8, in <module>
    asst.submit_order_by_stock(sku_ids='100006248177', area='19_1704_1797_37820',interval=1)
  File "C:\Users\Theo\Downloads\jd-assistant-master\jd_assistant.py", line 874, in submit_order_by_stock
    if self.if_item_can_be_ordered(sku_ids=sku_ids, area=area):
  File "C:\Users\Theo\Downloads\jd-assistant-master\jd_assistant.py", line 544, in if_item_can_be_ordered
    else self.get_single_item_stock(sku_id=sku_ids[0], area=area)
  File "C:\Users\Theo\Downloads\jd-assistant-master\jd_assistant.py", line 441, in get_single_item_stock
    resp = requests.get(url=url, params=payload, headers=headers)
  File "C:\Users\Theo\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Theo\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Theo\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Theo\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Theo\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='c0.3.cn', port=443): Max retries exceeded with url: /stock?skuId=100006248177&buyNum=1&area=19_1704_1797_37820&ch=1&_=1580224794754&callback=jQuery4673409&extraParam=%7B%22originid%22%3A%221%22%7D&cat=9192%2C12190%2C1517&venderId=1000078145 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001B6EA20F6A0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

不知道是我网络原因还是啥....

**Comment by ntsafe** [comment]
Windows没测试过。centos还挺稳定的

**Comment by tychxn** [comment]
这个确实没有遇到过，有可能访问频率太高了被限制了

**Comment by tychxn** [comment]
感觉大家最近都刷的好频繁。。

**Comment by ntsafe** [comment]
能不能回答我的问题一下。如何有货设置单数量

**Comment by DDFTONE** [comment]
> Windows没测试过。centos还挺稳定的

看来得弄个centos环境了...

**Comment by DDFTONE** [comment]
> 这个确实没有遇到过，有可能访问频率太高了被限制了

我设置的1秒...应该没问题...就是时间一长就会出现这错误

**Comment by tychxn** [comment]
> > 这个确实没有遇到过，有可能访问频率太高了被限制了
> 
> 我设置的1秒...应该没问题...就是时间一长就会出现这错误

间隔interval设置大一些
