### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by wyap-echo** [tychxn/jd-assistant#55]
wyap@wyap-echo:~/jd-assistant$ python jd_assistant.py
Traceback (most recent call last):
  File "jd_assistant.py", line 13, in <module>
    from config import global_config
  File "/home/wyap/jd-assistant/config.py", line 4, in <module>
    import configparser
ImportError: No module named configparser

**Comment by tychxn** [comment]
程序入口在`main.py`，使用方式可以看一下wiki
