### ISSUE TITLE
您好，我的程序始终无法正常下单，提示以下错误，Keyerror:skuid，请问该怎么修改呢？

### ISSUE THREAD

**Issue by Harrymy** [tychxn/jd-assistant#66]
略懂一点点python，想了很久但还是没找出来解决方法，请您帮我看看行吗？感谢！

2020-02-04 00:14:23,455 INFO: 登录成功
2020-02-04 00:14:23,459 INFO: 下单模式：['2130957'] 任一商品有货并且未下架均会尝试下单
2020-02-04 00:14:24,250 INFO: 2130957 满足下单条件，开始执行
Traceback (most recent call last):
  File "C:\Users\13673\Desktop\jd-assistant-master\有货提交订单.py", line 10, in <module>
    asst.buy_item_in_stock(sku_ids=sku_ids, area=area , wait_all=False, stock_interval=5)
  File "C:\Users\13673\Desktop\jd-assistant-master\util.py", line 165, in new_func
    return func(self, *args, **kwargs)
  File "C:\Users\13673\Desktop\jd-assistant-master\jd_assistant.py", line 1335, in buy_item_in_stock
    self._add_or_change_cart_item(self.get_cart_detail(), sku_id, count)
  File "C:\Users\13673\Desktop\jd-assistant-master\util.py", line 165, in new_func
    return func(self, *args, **kwargs)
  File "C:\Users\13673\Desktop\jd-assistant-master\jd_assistant.py", line 657, in get_cart_detail
    sku_id = item['skuid']  # 商品id
  File "C:\Users\13673\AppData\Local\Programs\Python\Python38\lib\site-packages\bs4\element.py", line 1321, in __getitem__
    return self.attrs[key]
KeyError: 'skuid'

**Comment by tychxn** [comment]
- 确认地址id有没有对
- 手工清空购物车重试
