### ISSUE TITLE
异常退出

### ISSUE THREAD

**Issue by PHCSJC** [tychxn/jd-assistant#77]
2020-02-07 18:53:11,230 ERROR: 查询 100011293950 库存信息异常：HTTPSConnectionPool(host='c0.3.cn', port=443): Max retries exceeded with url: /stock?skuId=100011293950&buyNum=2&area=1_2808_51536_0&ch=1&_=1581072791228&callback=jQuery1105779&extraParam=%7B%22originid%22%3A%221%22%7D&cat=9192%2C12190%2C1517&venderId=1000078145 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f123b387e80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f123b387e80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='c0.3.cn', port=443): Max retries exceeded with url: /stock?skuId=100011293950&buyNum=2&area=1_2808_51536_0&ch=1&_=1581072791228&callback=jQuery1105779&extraParam=%7B%22originid%22%3A%221%22%7D&cat=9192%2C12190%2C1517&venderId=1000078145 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f123b387e80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/jd-assistant-master/jd_assistant.py", line 456, in get_single_item_stock
    resp = requests.get(url=url, params=payload, headers=headers, timeout=self.timeout)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='c0.3.cn', port=443): Max retries exceeded with url: /stock?skuId=100011293950&buyNum=2&area=1_2808_51536_0&ch=1&_=1581072791228&callback=jQuery1105779&extraParam=%7B%22originid%22%3A%221%22%7D&cat=9192%2C12190%2C1517&venderId=1000078145 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f123b387e80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    asst.buy_item_in_stock(sku_ids=sku_ids, area=area, wait_all=False, stock_interval=3)
  File "/root/jd-assistant-master/util.py", line 167, in new_func
    return func(self, *args, **kwargs)
  File "/root/jd-assistant-master/jd_assistant.py", line 1362, in buy_item_in_stock
    if not self.if_item_can_be_ordered(sku_ids={sku_id: count}, area=area_id):
  File "/root/jd-assistant-master/util.py", line 167, in new_func
    return func(self, *args, **kwargs)
  File "/root/jd-assistant-master/jd_assistant.py", line 592, in if_item_can_be_ordered
    return self.get_single_item_stock(sku_id=sku_id, num=count, area=area_id)
  File "/root/jd-assistant-master/jd_assistant.py", line 461, in get_single_item_stock
    raise AsstException('查询 %s 库存信息异常：%s' % (sku_id, e))
exception.AsstException: 查询 100011293950 库存信息异常：HTTPSConnectionPool(host='c0.3.cn', port=443): Max retries exceeded with url: /stock?skuId=100011293950&buyNum=2&area=1_2808_51536_0&ch=1&_=1581072791228&callback=jQuery1105779&extraParam=%7B%22originid%22%3A%221%22%7D&cat=9192%2C12190%2C1517&venderId=1000078145 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f123b387e80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Comment by tychxn** [comment]
研究一下

**Comment by icelasa** [comment]
> ## 研究一下
> 看起来像是网络问题，因为这个查询库存接口不需要登陆

应该是挂代理了，你取消试试。我之前也出现过。

**Comment by tychxn** [comment]
Thanks. @icelasa

**Comment by PHCSJC** [comment]
@icelasa linux系统上跑的，也没有挂代理

**Comment by PHCSJC** [comment]
@tychxn 今天又有什么异常退出的

2020-02-08 09:11:06,157 INFO: 65425149164 不满足下单条件，3s后进行下一次查询
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    asst.buy_item_in_stock(sku_ids=sku_ids, area=area, wait_all=False, stock_interval=3)
  File "/root/jd-assistant-master/util.py", line 167, in new_func
    return func(self, *args, **kwargs)
  File "/root/jd-assistant-master/jd_assistant.py", line 1362, in buy_item_in_stock
    if not self.if_item_can_be_ordered(sku_ids={sku_id: count}, area=area_id):
  File "/root/jd-assistant-master/util.py", line 167, in new_func
    return func(self, *args, **kwargs)
  File "/root/jd-assistant-master/jd_assistant.py", line 592, in if_item_can_be_ordered
    return self.get_single_item_stock(sku_id=sku_id, num=count, area=area_id)
  File "/root/jd-assistant-master/jd_assistant.py", line 464, in get_single_item_stock
    sku_state = resp_json['stock']['skuState']  # 商品是否上架
KeyError: 'skuState'

**Comment by tychxn** [comment]
> @tychxn 今天又有一个异常退出的
> 
> 2020-02-08 09:11:06,157 INFO: 65425149164 不满足下单条件，3s后进行下一次查询
> Traceback (most recent call last):
> File "main.py", line 10, in
> asst.buy_item_in_stock(sku_ids=sku_ids, area=area, wait_all=False, stock_interval=3)
> File "/root/jd-assistant-master/util.py", line 167, in new_func
> return func(self, *args, **kwargs)
> File "/root/jd-assistant-master/jd_assistant.py", line 1362, in buy_item_in_stock
> if not self.if_item_can_be_ordered(sku_ids={sku_id: count}, area=area_id):
> File "/root/jd-assistant-master/util.py", line 167, in new_func
> return func(self, *args, **kwargs)
> File "/root/jd-assistant-master/jd_assistant.py", line 592, in if_item_can_be_ordered
> return self.get_single_item_stock(sku_id=sku_id, num=count, area=area_id)
> File "/root/jd-assistant-master/jd_assistant.py", line 464, in get_single_item_stock
> sku_state = resp_json['stock']['skuState'] # 商品是否上架
> KeyError: 'skuState'

等下修复

**Comment by whwnow** [comment]
我也遇到这个问题了，每次运行几小时就会异常退出，不知道是不是一个原因造成的，错误代码如下。

```
2020-02-08 23:09:25,280 ERROR: 查询 4642397 库存信息异常：HTTPSConnectionPool(host='c0.3.cn', port=443): Max retries exceeded with url: /stock?skuId=4642397&buyNum=5&area=1_72_2839_0&ch=1&_=1581174555260&callback=jQuery9416069&extraParam=%7B%22originid%22%3A%221%22%7D&cat=14065%2C14099%2C14101&venderId=1000092342 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f38de45b828>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/user/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/user/.local/lib/python3.6/site-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/home/user/.local/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f38de45b828>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/user/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='c0.3.cn', port=443): Max retries exceeded with url: /stock?skuId=4642397&buyNum=5&area=1_72_2839_0&ch=1&_=1581174555260&callback=jQuery9416069&extraParam=%7B%22originid%22%3A%221%22%7D&cat=14065%2C14099%2C14101&venderId=1000092342 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f38de45b828>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/d/Coder/jd-assistant-master/jd_assistant.py", line 456, in get_single_item_stock
    resp = requests.get(url=url, params=payload, headers=headers, timeout=self.timeout)
  File "/home/user/.local/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='c0.3.cn', port=443): Max retries exceeded with url: /stock?skuId=4642397&buyNum=5&area=1_72_2839_0&ch=1&_=1581174555260&callback=jQuery9416069&extraParam=%7B%22originid%22%3A%221%22%7D&cat=14065%2C14099%2C14101&venderId=1000092342 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f38de45b828>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 28, in <module>
    asst.buy_item_in_stock(sku_ids=sku_ids, area=area, wait_all=False, stock_interval=1)
  File "/mnt/d/Coder/jd-assistant-master/util.py", line 167, in new_func
    return func(self, *args, **kwargs)
  File "/mnt/d/Coder/jd-assistant-master/jd_assistant.py", line 1362, in buy_item_in_stock
    if not self.if_item_can_be_ordered(sku_ids={sku_id: count}, area=area_id):
  File "/mnt/d/Coder/jd-assistant-master/util.py", line 167, in new_func
    return func(self, *args, **kwargs)
  File "/mnt/d/Coder/jd-assistant-master/jd_assistant.py", line 592, in if_item_can_be_ordered
    return self.get_single_item_stock(sku_id=sku_id, num=count, area=area_id)
  File "/mnt/d/Coder/jd-assistant-master/jd_assistant.py", line 461, in get_single_item_stock
    raise AsstException('查询 %s 库存信息异常：%s' % (sku_id, e))
exception.AsstException: 查询 4642397 库存信息异常：HTTPSConnectionPool(host='c0.3.cn', port=443): Max retries exceeded with url: /stock?skuId=4642397&buyNum=5&area=1_72_2839_0&ch=1&_=1581174555260&callback=jQuery9416069&extraParam=%7B%22originid%22%3A%221%22%7D&cat=14065%2C14099%2C14101&venderId=1000092342 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f38de45b828>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))```

**Comment by whwnow** [comment]
更新最新代码之后再次遇到上面的报错信息

**Comment by tufu9441** [comment]
我也遇到了同样的问题，运行一段时间后就会退出。
```
2020-02-09 05:01:03,374 ERROR: 查询 3649920 库存信息异常：HTTPSConnectionPool(host='c0.3.cn', port=443): Max retries exceeded with url: /stock?cat=9192%2C12190%2C1517&_=1581224458368&ch=1&area=1_2800_2850_0&skuId=3649920&extraParam=%7B%22originid%22%3A%221%22%7D&venderId=1000084390&callback=jQuery5474550&buyNum=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb13e0dea58>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

**Comment by PHCSJC** [comment]
又一次异常退出，大佬帮忙：

`2020-02-13 11:34:18,006 INFO: 6046611 不满足下单条件，3s后进行下一次查询
Traceback (most recent call last):
  File "main.py2", line 10, in <module>
    asst.buy_item_in_stock(sku_ids=sku_ids, area=area, wait_all=False, stock_interval=3)
  File "/root/jd-assistant-master/util.py", line 220, in new_func
    return func(self, *args, **kwargs)
  File "/root/jd-assistant-master/jd_assistant.py", line 1366, in buy_item_in_stock
    if not self.if_item_can_be_ordered(sku_ids={sku_id: count}, area=area_id):
  File "/root/jd-assistant-master/util.py", line 220, in new_func
    return func(self, *args, **kwargs)
  File "/root/jd-assistant-master/jd_assistant.py", line 596, in if_item_can_be_ordered
    return self.get_single_item_stock(sku_id=sku_id, num=count, area=area_id)
  File "/root/jd-assistant-master/jd_assistant.py", line 463, in get_single_item_stock
    resp_json = parse_json(resp.text)
  File "/root/jd-assistant-master/util.py", line 122, in parse_json
    return json.loads(s[begin:end])
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)`

**Comment by PHCSJC** [comment]
刚才再次异常退出，大佬请看：

`2020-02-13 20:32:28,095 ERROR: 查询 6046613 库存信息异常：HTTPSConnectionPool(host='c0.3.cn', port=443): Max retries exceeded with url: /stock?skuId=6046613&buyNum=2&area=1_2808_51536_0&ch=1&_=1581597133046&callback=jQuery8566020&extraParam=%7B%22originid%22%3A%221%22%7D&cat=9192%2C12190%2C1517&venderId=1000009116 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f29de2a0128>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f29de2a0128>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='c0.3.cn', port=443): Max retries exceeded with url: /stock?skuId=6046613&buyNum=2&area=1_2808_51536_0&ch=1&_=1581597133046&callback=jQuery8566020&extraParam=%7B%22originid%22%3A%221%22%7D&cat=9192%2C12190%2C1517&venderId=1000009116 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f29de2a0128>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/jd-assistant-master/jd_assistant.py", line 456, in get_single_item_stock
    resp = requests.get(url=url, params=payload, headers=headers, timeout=self.timeout)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='c0.3.cn', port=443): Max retries exceeded with url: /stock?skuId=6046613&buyNum=2&area=1_2808_51536_0&ch=1&_=1581597133046&callback=jQuery8566020&extraParam=%7B%22originid%22%3A%221%22%7D&cat=9192%2C12190%2C1517&venderId=1000009116 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f29de2a0128>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py2", line 10, in <module>
    asst.buy_item_in_stock(sku_ids=sku_ids, area=area, wait_all=False, stock_interval=3)
  File "/root/jd-assistant-master/util.py", line 220, in new_func
    return func(self, *args, **kwargs)
  File "/root/jd-assistant-master/jd_assistant.py", line 1366, in buy_item_in_stock
    if not self.if_item_can_be_ordered(sku_ids={sku_id: count}, area=area_id):
  File "/root/jd-assistant-master/util.py", line 220, in new_func
    return func(self, *args, **kwargs)
  File "/root/jd-assistant-master/jd_assistant.py", line 596, in if_item_can_be_ordered
    return self.get_single_item_stock(sku_id=sku_id, num=count, area=area_id)
  File "/root/jd-assistant-master/jd_assistant.py", line 461, in get_single_item_stock
    raise AsstException('查询 %s 库存信息异常：%s' % (sku_id, e))
exception.AsstException: 查询 6046613 库存信息异常：HTTPSConnectionPool(host='c0.3.cn', port=443): Max retries exceeded with url: /stock?skuId=6046613&buyNum=2&area=1_2808_51536_0&ch=1&_=1581597133046&callback=jQuery8566020&extraParam=%7B%22originid%22%3A%221%22%7D&cat=9192%2C12190%2C1517&venderId=1000009116 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f29de2a0128>: Failed to establish a new connection: [Errno -2] Name or service not known',))`

**Comment by bearqq** [comment]
> 
> 
> 我也遇到了同样的问题，运行一段时间后就会退出。
> 
> ```
> 2020-02-09 05:01:03,374 ERROR: 查询 3649920 库存信息异常：HTTPSConnectionPool(host='c0.3.cn', port=443): Max retries exceeded with url: /stock?cat=9192%2C12190%2C1517&_=1581224458368&ch=1&area=1_2800_2850_0&skuId=3649920&extraParam=%7B%22originid%22%3A%221%22%7D&venderId=1000084390&callback=jQuery5474550&buyNum=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb13e0dea58>: Failed to establish a new connection: [Errno -2] Name or service not known',))
> ```

大魔在github上搜搜别的repo试试，虽然我也就没抢到过
