### ISSUE TITLE
运行一段时间会提示KeyError: 'skuState' 请问怎么修改

### ISSUE THREAD

**Issue by Hywans** [tychxn/jd-assistant#78]
2020-02-07 22:37:10,948 INFO: 100006877166 不满足下单条件，0.1s后进行下一次查询
2020-02-07 22:37:11,267 INFO: 5481126 不满足下单条件，0.1s后进行下一次查询
Traceback (most recent call last):
  File "D:/Desktop/jd-assistant-master/m4.py", line 9, in <module>
    asst.buy_item_in_stock(sku_ids=sku_ids, area=area, wait_all=False, stock_interval=0.1)
  File "D:\Desktop\jd-assistant-master\util.py", line 167, in new_func
    return func(self, *args, **kwargs)
  File "D:\Desktop\jd-assistant-master\jd_assistant.py", line 1367, in buy_item_in_stock
    if not self.if_item_can_be_ordered(sku_ids={sku_id: count}, area=area_id):
  File "D:\Desktop\jd-assistant-master\util.py", line 167, in new_func
    return func(self, *args, **kwargs)
  File "D:\Desktop\jd-assistant-master\jd_assistant.py", line 597, in if_item_can_be_ordered
    return self.get_single_item_stock(sku_id=sku_id, num=count, area=area_id)
  File "D:\Desktop\jd-assistant-master\jd_assistant.py", line 469, in get_single_item_stock
    sku_state = resp_json['stock']['skuState']  # 商品是否上架
KeyError: 'skuState'

**Comment by Hywans** [comment]
运行一段时间会提示KeyError: 'skuState'   请问怎么修改

**Comment by ShmilyChen** [comment]
使用get方法
```
stock_info = resp_json.get('stock')
        if stock_info is None:
            logger.error('查询 %s 库存信息异常', sku_id)
            return False
        # sku_state = resp_json['stock']['skuState']  # 商品是否上架
        # stock_state = resp_json['stock']['StockState']  # 商品库存状态：33 -- 现货  0,34 -- 无货  36 -- 采购中  40 -- 可配货
        sku_state = stock_info.get('skuState')  # 商品是否上架
        stock_state = stock_info.get('StockState')  # 商品库存状态：33 -- 现货  0,34 -- 无货  36 -- 采购中  40 -- 可配货
```

**Comment by Hywans** [comment]
> 使用get方法
> 
> ```
> stock_info = resp_json.get('stock')
>         if stock_info is None:
>             logger.error('查询 %s 库存信息异常', sku_id)
>             return False
>         # sku_state = resp_json['stock']['skuState']  # 商品是否上架
>         # stock_state = resp_json['stock']['StockState']  # 商品库存状态：33 -- 现货  0,34 -- 无货  36 -- 采购中  40 -- 可配货
>         sku_state = stock_info.get('skuState')  # 商品是否上架
>         stock_state = stock_info.get('StockState')  # 商品库存状态：33 -- 现货  0,34 -- 无货  36 -- 采购中  40 -- 可配货
> ```
谢谢大佬 我试试

**Comment by tychxn** [comment]
> 使用get方法
> 
> ```
> stock_info = resp_json.get('stock')
>         if stock_info is None:
>             logger.error('查询 %s 库存信息异常', sku_id)
>             return False
>         # sku_state = resp_json['stock']['skuState']  # 商品是否上架
>         # stock_state = resp_json['stock']['StockState']  # 商品库存状态：33 -- 现货  0,34 -- 无货  36 -- 采购中  40 -- 可配货
>         sku_state = stock_info.get('skuState')  # 商品是否上架
>         stock_state = stock_info.get('StockState')  # 商品库存状态：33 -- 现货  0,34 -- 无货  36 -- 采购中  40 -- 可配货
> ```

thx. 是不是监控久了京东接口返回的数据格式变化了，测试过程中没有遇到这种问题

**Comment by tychxn** [comment]
代码已经 fix.

**Comment by Hywans** [comment]
> > 使用get方法
> > ```
> > stock_info = resp_json.get('stock')
> >         if stock_info is None:
> >             logger.error('查询 %s 库存信息异常', sku_id)
> >             return False
> >         # sku_state = resp_json['stock']['skuState']  # 商品是否上架
> >         # stock_state = resp_json['stock']['StockState']  # 商品库存状态：33 -- 现货  0,34 -- 无货  36 -- 采购中  40 -- 可配货
> >         sku_state = stock_info.get('skuState')  # 商品是否上架
> >         stock_state = stock_info.get('StockState')  # 商品库存状态：33 -- 现货  0,34 -- 无货  36 -- 采购中  40 -- 可配货
> > ```
> 
> thx. 是不是监控久了京东接口返回的数据格式变化了，测试过程中没有遇到这种问题
> 
> @Hywans 能不能加一条 `logger.info(resp_json)` 看一下响应数据格式是不是变化了

我试了下前面的格式都没有变，到出错这一行就不输出响应数据了，不知道什么原因，换了get今天跑了一天都没有出现这个问题。

2020-02-08 21:47:26,082 INFO: 100006784128 不满足下单条件，0.1s后进行下一次查询
Traceback (most recent call last):
  File "D:/Desktop/jd-assistant-master/m5.py", line 9, in <module>
    asst.buy_item_in_stock(sku_ids=sku_ids, area=area, wait_all=False, stock_interval=0.1)
  File "D:\Desktop\jd-assistant-master\util.py", line 167, in new_func
    return func(self, *args, **kwargs)
  File "D:\Desktop\jd-assistant-master\jd_assistant.py", line 1370, in buy_item_in_stock
    if not self.if_item_can_be_ordered(sku_ids={sku_id: count}, area=area_id):
  File "D:\Desktop\jd-assistant-master\util.py", line 167, in new_func
    return func(self, *args, **kwargs)
  File "D:\Desktop\jd-assistant-master\jd_assistant.py", line 600, in if_item_can_be_ordered
    return self.get_single_item_stock(sku_id=sku_id, num=count, area=area_id)
  File "D:\Desktop\jd-assistant-master\jd_assistant.py", line 469, in get_single_item_stock
    sku_state = resp_json['stock']['skuState']  # 商品是否上架
KeyError: 'skuState'

Process finished with exit code 1
