### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by QAQxxl** [tychxn/jd-assistant#81]
Traceback (most recent call last):
  File "D:\Program Files (x86)\下载\jd-assistant-master\main.py", line 3, in <module>
    from jd_assistant import Assistant
  File "D:\Program Files (x86)\下载\jd-assistant-master\jd_assistant.py", line 13, in <module>
    from config import global_config
  File "D:\Program Files (x86)\下载\jd-assistant-master\config.py", line 23, in <module>
    global_config = Config()
  File "D:\Program Files (x86)\下载\jd-assistant-master\config.py", line 12, in __init__
    raise FileNotFoundError("No such file: config.ini")
FileNotFoundError: No such file: config.ini

**Comment by zs-liu** [comment]
在`config.py`同目录下应该有一个`config.ini`文件，文件具体内容参见项目Wiki中的`3.常见问题`
（难道是不小心把`config.ini`删了？

**Comment by QAQxxl** [comment]
![批注 2020-02-08 171226](https://user-images.githubusercontent.com/35886796/74082596-a3178980-4a96-11ea-9f68-4db16ebce45c.png)
没有删掉

**Comment by zs-liu** [comment]
我猜测是运行的路径不对，`os.getcwd()`这个可能返回的是你C盘的路径
你可以在这个`jd-assistant-master`下运行python试一下么？或者看看`os.getcwd()`的结果是啥？

**Comment by QAQxxl** [comment]
好的，我已解决问题，谢谢

**Comment by QAQxxl** [comment]
Traceback (most recent call last):
  File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1322, in getresponse
    response.begin()
  File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 439, in send    resp = conn.urlopen(
  File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='item.jd.com', port=443): Max retries exceeded with url: /1835967.html (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files (x86)\jd-assistant-master\main.py", line 17, in <module>
    asst.buy_item_in_stock(sku_ids=sku_ids, area=area, wait_all=False, stock_interval=5)
  File "D:\Program Files (x86)\jd-assistant-master\util.py", line 167, in new_func
    return func(self, *args, **kwargs)
  File "D:\Program Files (x86)\jd-assistant-master\jd_assistant.py", line 1366, in buy_item_in_stock
    if not self.if_item_can_be_ordered(sku_ids={sku_id: count}, area=area_id):
  File "D:\Program Files (x86)\jd-assistant-master\util.py", line 167, in new_func
    return func(self, *args, **kwargs)
  File "D:\Program Files (x86)\jd-assistant-master\jd_assistant.py", line 596, in if_item_can_be_ordered
    return self.get_single_item_stock(sku_id=sku_id, num=count, area=area_id)
  File "D:\Program Files (x86)\jd-assistant-master\jd_assistant.py", line 430, in get_single_item_stock
    page = self._get_item_detail_page(sku_id)
  File "D:\Program Files (x86)\jd-assistant-master\jd_assistant.py", line 415, in _get_item_detail_page
    page = requests.get(url=url, headers=self.headers)
  File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 646, in send    r = adapter.send(request, **kwargs)
  File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 510, in send    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='item.jd.com', port=443): Max retries exceeded with url: /1835967.html (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
运行一小会又出现了这个

**Comment by zs-liu** [comment]
> Traceback (most recent call last):
> File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
> httplib_response = self._make_request(
> File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
> six.raise_from(e, None)
> File "", line 3, in raise_from
> File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
> httplib_response = conn.getresponse()
> File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1322, in getresponse
> response.begin()
> File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 303, in begin
> version, status, reason = self._read_status()
> File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 272, in _read_status
> raise RemoteDisconnected("Remote end closed connection without"
> http.client.RemoteDisconnected: Remote end closed connection without response
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 439, in send resp = conn.urlopen(
> File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 719, in urlopen
> retries = retries.increment(
> File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 436, in increment
> raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='item.jd.com', port=443): Max retries exceeded with url: /1835967.html (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "D:\Program Files (x86)\jd-assistant-master\main.py", line 17, in
> asst.buy_item_in_stock(sku_ids=sku_ids, area=area, wait_all=False, stock_interval=5)
> File "D:\Program Files (x86)\jd-assistant-master\util.py", line 167, in new_func
> return func(self, *args, **kwargs)
> File "D:\Program Files (x86)\jd-assistant-master\jd_assistant.py", line 1366, in buy_item_in_stock
> if not self.if_item_can_be_ordered(sku_ids={sku_id: count}, area=area_id):
> File "D:\Program Files (x86)\jd-assistant-master\util.py", line 167, in new_func
> return func(self, *args, **kwargs)
> File "D:\Program Files (x86)\jd-assistant-master\jd_assistant.py", line 596, in if_item_can_be_ordered
> return self.get_single_item_stock(sku_id=sku_id, num=count, area=area_id)
> File "D:\Program Files (x86)\jd-assistant-master\jd_assistant.py", line 430, in get_single_item_stock
> page = self._get_item_detail_page(sku_id)
> File "D:\Program Files (x86)\jd-assistant-master\jd_assistant.py", line 415, in _get_item_detail_page
> page = requests.get(url=url, headers=self.headers)
> File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 75, in get
> return request('get', url, params=params, **kwargs)
> File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 60, in request
> return session.request(method=method, url=url, **kwargs)
> File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 533, in request
> resp = self.send(prep, **send_kwargs)
> File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 646, in send r = adapter.send(request, **kwargs)
> File "C:\Users\14510\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 510, in send raise ProxyError(e, request=request)
> requests.exceptions.ProxyError: HTTPSConnectionPool(host='item.jd.com', port=443): Max retries exceeded with url: /1835967.html (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
> 运行一小会又出现了这个

试试重新联网或者关闭代理 :) 我对网络问题一窍不通

**Comment by QAQxxl** [comment]
谢谢，我也觉得是网络问题。

**Comment by tychxn** [comment]
应该是开了代理导致的，关掉试试

**Comment by hong99yy** [comment]
> 好的，我已解决问题，谢谢

请问你是如何解决的，我也遇到同样的问题
