### ISSUE TITLE
AttributeError: 'int' object has no attribute 'split'  请问怎么修改？

### ISSUE THREAD

**Issue by zlj6856** [tychxn/jd-assistant#92]
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    asst.buy_item_in_stock(sku_ids=sku_ids, area=area, wait_all=False, stock_interval=3)
  File "/Users/zho/Downloads/jd-assistant/util.py", line 167, in new_func
    return func(self, *args, **kwargs)
  File "/Users/zho/Downloads/jd-assistant/jd_assistant.py", line 1358, in buy_item_in_stock
    items_dict = parse_sku_id(sku_ids)
  File "/Users/zho/Downloads/jd-assistant/util.py", line 109, in parse_sku_id
    sku_id_list = list(filter(bool, map(lambda x: x.strip(), sku_ids.split(','))))
AttributeError: 'int' object has no attribute 'split'

**Comment by tychxn** [comment]
商品id使用字符串即可
