### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by hangyi2004** [tychxn/jd-assistant#95]
错误提示，一会儿就自动关闭了
Traceback (most recent call last):
  File "D:\Users\Desktop\jd-assistant-master\main.py", line 18, in <module>
      asst.buy_item_in_stock(sku_ids=sku_ids,area=area,stock_interval=1)
  File "D:\Users\Desktop\jd-assistant-master\util.py", line 220, in new_func
      return func(self, *args, **kwargs)
  File "D:\Users\Desktop\jd-assistant-master\jd_assistant.py", line 1366, in buy_item_in_stock
      if not self.if_item_can_be_ordered(sku_ids={sku_id: count}, area=area_id):
  File "D:\Users\Desktop\jd-assistant-master\util.py", line 220, in new_func
      return func(self, *args, **kwargs)
  File "D:\Users\Desktop\jd-assistant-master\jd_assistant.py", line 596, in if_item_can_be_ordered
      return self.get_single_item_stock(sku_id=sku_id, num=count, area=area_id)
  File "D:\Users\Desktop\jd-assistant-master\jd_assistant.py", line 432, in get_single_item_stock
      cat = match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
大佬知道怎么解决吗？

**Comment by tychxn** [comment]
贴一下调用代码，考虑是商品id填写错误

**Comment by jy024929** [comment]
因为有一个商品已经被删除了，就会跳这个
